<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-29T10:41:52 EST" name="Default suite" finished-at="2024-11-29T10:42:31 EST" duration-ms="39619">
    <groups>
    </groups>
    <test started-at="2024-11-29T10:41:52 EST" name="Default test" finished-at="2024-11-29T10:42:31 EST" duration-ms="39619">
      <class name="com.cgi.test.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.cgi.test.LoginTest@25ce9dc4]" started-at="2024-11-29T10:41:52 EST" name="setup" finished-at="2024-11-29T10:42:01 EST" duration-ms="9606" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="InvalidLoginTest()[pri:0, instance:com.cgi.test.LoginTest@25ce9dc4]" started-at="2024-11-29T10:42:01 EST" name="InvalidLoginTest" finished-at="2024-11-29T10:42:08 EST" duration-ms="7035" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [We do not recognize your credentials, please try another combination.] but found [We do not recognize your credentials, please try another combination.
Log In
© Vitech Systems Group, Inc. All Rights Reserved]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [We do not recognize your credentials, please try another combination.] but found [We do not recognize your credentials, please try another combination.
Log In
© Vitech Systems Group, Inc. All Rights Reserved]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.cgi.test.LoginTest.InvalidLoginTest(LoginTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidLoginTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.cgi.test.LoginTest@25ce9dc4]" started-at="2024-11-29T10:42:08 EST" name="teardown" finished-at="2024-11-29T10:42:10 EST" duration-ms="1762" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.cgi.test.LoginTest@25ce9dc4]" started-at="2024-11-29T10:42:10 EST" name="setup" finished-at="2024-11-29T10:42:20 EST" duration-ms="9676" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validLoginTest()[pri:0, instance:com.cgi.test.LoginTest@25ce9dc4]" started-at="2024-11-29T10:42:20 EST" name="validLoginTest" finished-at="2024-11-29T10:42:30 EST" duration-ms="9884" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.cgi.test.LoginTest@25ce9dc4]" started-at="2024-11-29T10:42:30 EST" name="teardown" finished-at="2024-11-29T10:42:31 EST" duration-ms="1571" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.cgi.test.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
